name: Reusable Workflow Source

on:
  workflow_call:
    inputs:
      node-version:
        description: "Node.js version"
        required: true
        default: "18"
        type: string
      run-lint:
        description: "Run lint"
        required: true
        default: true
        type: boolean
    outputs:
      status:
        description: "status"
        value: ${{ jobs.build-test.outputs.status }}

jobs:
  build-test:
    runs-on: ${{ matrix.os }}
    outputs:
      status: ${{ steps.set-output-status.outputs.status }}

    strategy:
      fail-fast: true
      matrix:
        node-version: ["18", "20"]
        os: ["ubuntu-latest"]

    steps:
      - name: Setup Node.js
        uses: ../actions/setup-node
        with:
          node-version: ${{ inputs.node-version }}

      - name: Run Build
        run: npm run build

      - name: Run Lint
        if: ${{ inputs.run-lint }}
        run: npm run lint

      - name: Run test
        id: test
        run: |
          npm run test
        shell: bash

      - name: Set output status
        id: set-output-status
        run: |
          if [ "${{ steps.test.outputs.status }}" = "success" ]; then
            echo "status=success" >> "$GITHUB_OUTPUT"
          elif [ "${{ steps.test.outputs.status }}" = "failure" ]; then
            echo "status=failure" >> "$GITHUB_OUTPUT"
          fi
        shell: bash
